Upgrade to CKAN 2.11
fjelltopp/ckanext-googleanalytics4 pull request #2
Opened 2024-11-28 10:07 UTC by ntwalibas

## Description

This PR performs  a major refactoring and enhancement:
- It refactors the old structure of the extension so it follows the structure of our existing extensions,
- It adds a functionality to track the number of page views.

It remains to have the following properly implemented:
- Make sure to delete package and resource download data when the corresponding dataset/resource are deleted.
 
## Testing
Tests to follow while functionality is being reviewed.

## Documentation
The documentation needs to be improved so it is easier to install this extension in new projects.

## Checklist
- [ ] The Jira ticket for this issue has been updated to "Ready to Review" or equivalent.
- [x] I have developed these changes in discussion with the appropriate project manager.
- [x] My code follows the general Fjelltopp documentation (see Confluence).
- [ ] I have made corresponding changes to the Fjelltopp documentation (see Confluence).
- [x] I have rebased this branch with master.
- [ ] New dependency changes have been committed.
- [ ] I have added automated tests that prove my fix is effective or that my feature works.
- [ ] New and existing tests pass locally with my changes.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [ ] I have assigned at least one label to this PR: "patch", "minor", "major".

2024-12-04 10:30 UTC, ChasNelson1990 commented
@ntwalibas - should we add a release tag to the previous version so that projects can continue to easily use the version from before the 2.11 migration

2024-12-05 12:44 UTC, jonathansberry requested changes
Wow this is a big change though!  Hope it's all been properly tested. A couple of small comments from perusing through, but it's such a large PR it's difficult to check coherence in any meaningful way by review.

2024-12-05 12:44 UTC, jonathansberry commented on ckanext/googleanalytics/blueprints/googleanalytics_blueprint.py
> +from ckan.common import g
Can get this from the toolkit: `toolkit.g`

2024-12-05 12:44 UTC, jonathansberry commented on ckanext/googleanalytics/logic.py
> +    package = toolkit.get_action("package_show")(context, {"id": path_id})
It is my understanding that `toolkit.get_action` automatically adds the model and session and user to the context.  I believe this also means you don't need to import the model. 
```suggestion
    package = toolkit.get_action("package_show")({}, {"id": path_id})
```

2026-05-19 14:10 UTC, closed without merging